Drop Python 3.3 testing
It's failing on tests for flake8 which dies with:

```
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/flake8/plugins/manager.py", line 5, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
```

Also most Django versions we test on don't support it, and it's EOL.